"""API models."""
from .schemas import (
    StationMetadata,
    WeatherReading,
    LatestReadingsResponse,
    HistoricalDataResponse,
    ForecastPoint,
    ForecastResponse,
    RegionalForecastResponse,
    NetworkNode,
    NetworkEdge,
    NetworkAnalysisResponse,
    FlowPattern,
    FlowAnalysisResponse,
    BathymetryInfo,
    ErrorResponse,
    HistoricalDataRequest,
    ForecastRequest,
    RegionalForecastRequest,
)

__all__ = [
    "StationMetadata",
    "WeatherReading",
    "LatestReadingsResponse",
    "HistoricalDataResponse",
    "ForecastPoint",
    "ForecastResponse",
    "RegionalForecastResponse",
    "NetworkNode",
    "NetworkEdge",
    "NetworkAnalysisResponse",
    "FlowPattern",
    "FlowAnalysisResponse",
    "BathymetryInfo",
    "ErrorResponse",
    "HistoricalDataRequest",
    "ForecastRequest",
    "RegionalForecastRequest",
]
